### PR TITLE
Add ruby 2.2.3, gemset 'ostx-rescue-from'

### PR DESCRIPTION
**Pull request by joemsak**
Right off the bat, can I get this :)

### CODE REVIEW

**Comment by jpslav** [comment]
Do we want to specify the ruby version in the Gemfile?  Does that apply to all users of the gem or just in dev?

**Comment by joemsak** [comment]
When in the Gemfile it's just during development

**Comment by jpslav** [comment]
also is the compatible with rvm rbenv dev?

**Comment by joemsak** [comment]
I did this to work seamlessly with rvm, I don't know what rbenv users are required to do, but this won't get in their way

**Comment by Dantemss** [comment]
Huh seems odd to me how this even works... the Gemfile is read by bundler... by that point isn't it too late to specify the ruby version? You already loaded bundler for some other ruby version...

After looking at it, apparently all it does is to cause bundler to barf if the wrong version is loaded...

To actually force the ruby version, you need the .ruby-version file.

**Comment by joemsak** [comment]
All I know is RVM reads the settings in the Gemfile

**Comment by jpslav** [comment]
what about .ruby-version and .ruby-gemset which I believe are both rvm and rbenv compatible?

**Comment by joemsak** [comment]
Sure, it's just I figured I'd go with the file that already exists

**Comment by joemsak** [comment]
Fixed

**Pull request merged**
